### ISSUE TITLE
Coloured output needs to be configurable

### ISSUE THREAD

**Issue by domcleal** [dgoodwin/tito#182]
d489dd9 / 53144dc added coloured output to tito, but the blue is rather hard to read for me on a black background.

![screenshot from 2015-06-15 12 55 46](https://cloud.githubusercontent.com/assets/482089/8159372/ea85f97a-135d-11e5-8896-ed93c65de274.png)

tito should probably:

1. have a simple on/off config option for coloured output
2. have at least two built in colour schemes (dark/light)
3. possibly add the ability to configure colour schemes

**Comment by jumanjiman** [comment]
:+1:

**Comment by awood** [comment]
@domcleal I'm going to add a NO_COLOR option that can be set to '1' or to 'True' in ~/.titorc that will turn off colors.  Is that sufficient or would you also want an option to turn off colors for specific commands?  E.g. `tito build --no-color`.  (Keep in mind that python-blessings is smart enough not to output ANSI codes when output is being redirected)

Also, you might also consider tweaking your terminal colors a little so the blue is more visible since other programs are likely to use blue as well.  In gnome-terminal, you can just go to the color tab in Profile Preferences and lighten up that blue to a cyan or something.

**Comment by domcleal** [comment]
> I'm going to add a NO_COLOR option that can be set to '1' or to 'True' in ~/.titorc that will turn off colors. Is that sufficient or would you also want an option to turn off colors for specific commands?

Yep, that's sufficient, per-command isn't necessary.  I'd suggest calling it `COLOR` and defaulting to true, to avoid a double negative to disable it.

> Also, you might also consider tweaking your terminal colors a little so the blue is more visible since other programs are likely to use blue as well.

Yeah, this does happen occasionally, but most other programs are configurable :)
